// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVqOPuVKos79UMudCoNuRLbUVklHsrxtA',
    appId: '1:861824910619:web:c7f4c9514b6037c865ffbe',
    messagingSenderId: '861824910619',
    projectId: 'kangsayur-8136c',
    authDomain: 'kangsayur-8136c.firebaseapp.com',
    storageBucket: 'kangsayur-8136c.appspot.com',
    measurementId: 'G-WNTRK449TW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH059NmwuJxjrUFHY9rFy8mPgikd0l06M',
    appId: '1:861824910619:android:b53e6dd17d5941b565ffbe',
    messagingSenderId: '861824910619',
    projectId: 'kangsayur-8136c',
    storageBucket: 'kangsayur-8136c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwROe4ENsapO_LDocatD6ryEE7UC8Mgk4',
    appId: '1:861824910619:ios:52f036e4ea5895c865ffbe',
    messagingSenderId: '861824910619',
    projectId: 'kangsayur-8136c',
    storageBucket: 'kangsayur-8136c.appspot.com',
    iosClientId: '861824910619-1hicif0e6uctmru1v9etaq96g2elltv6.apps.googleusercontent.com',
    iosBundleId: 'com.example.kangsayurSeller',
  );
}
